name: ie-bank-infra

on:
  push:
      paths:
        - 'parameters/**'
        - '.github/**'
        - 'modules/**'
        - '!scripts/**'
      branches:
        - main
        - marc-new
      workflow_dispatch:
env:
  RESOURCE_GROUP_DEV: aguadamillas_students_1
  RESOURCE_GROUP_UAT: aguadamillas_students_1
  RESSOURCE_GROUP_PROD: aguadamillas_students_1
  SUBSCRIPTION_ID_DEV: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  SUBSCRIPTION_ID_UAT: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  SUBSCRIPTION_ID_PROD: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: cheblimarc4

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Lint Bicep code 
    - name: Run Bicep linter
      run: az bicep build --file ./main.bicep

  deploy-dev:
#   if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
    env:
      ENV: dev
      DBHOST: cheblimarc4-dbsrv-dev.postgres.database.azure.com
      DBNAME: cheblimarc4-db-dev
      FLASK_APP: app.py
      FLASK_DEBUG: 1
      

    steps:

      # Checkout code in main
    - uses: actions/checkout@main
    
      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
        resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
        template: ./main.bicep
        parameters: ./parameters/dev.parameters.json appServiceAPIEnvVarENV=${{ env.ENV }} appServiceAPIEnvVarDBHOST=${{ env.DBHOST }} appServiceAPIEnvVarDBNAME=${{ env.DBNAME }} appServiceAPIEnvVarDBPASS=${{ secrets.DBPASS }} appServiceAPIDBHostDBUSER=${{ secrets.DBUSER }} appServiceAPIDBHostFLASK_APP=${{ env.FLASK_APP }} appServiceAPIDBHostFLASK_DEBUG=${{ env.FLASK_DEBUG }}
        deploymentName: ${{ env.USER_ALIAS }}
      
  deploy-uat:
 #    if: github.ref == 'refs/heads/uat'
      runs-on: ubuntu-latest
      needs: [build, deploy-dev]
      environment:
        name: 'User Acceptance Testing'
      env:
          ENV: uat
          DBHOST: cheblimarc4-dbsrv-uat.postgres.database.azure.com
          DBNAME: cheblimarc4-db-uat
          FLASK_APP: app.py
          FLASK_DEBUG: 1
                
          
      steps: 
          
      # Checkout code in main
      - uses: actions/checkout@main
    
      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID_UAT }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_UAT }}
          template: ./main.bicep
          parameters: ./parameters/dev.parameters.json appServiceAPIEnvVarENV=${{ env.ENV }} appServiceAPIEnvVarDBHOST=${{ env.DBHOST }} appServiceAPIEnvVarDBNAME=${{ env.DBNAME }} appServiceAPIEnvVarDBPASS=${{ secrets.DBPASS }} appServiceAPIDBHostDBUSER=${{ secrets.DBUSER }} appServiceAPIDBHostFLASK_APP=${{ env.FLASK_APP }} appServiceAPIDBHostFLASK_DEBUG=${{ env.FLASK_DEBUG }}
          deploymentName: ${{ env.USER_ALIAS }}

    deploy-uat:
      #    if: github.ref == 'refs/heads/prod'
            runs-on: ubuntu-latest
            needs: [build, deploy-dev]
            environment:
              name: 'Production'
            env:
                ENV: uat
                DBHOST: cheblimarc4-dbsrv-prod.postgres.database.azure.com
                DBNAME: cheblimarc4-db-prod
                FLASK_APP: app.py
                FLASK_DEBUG: 1
                      
                
            steps: 
                
            # Checkout code in main
            - uses: actions/checkout@main
          
            # Log into Azure
            - uses: azure/login@v1
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}
      
            # Deploy Bicep file
            - name: deploy
              uses: azure/arm-deploy@v1
              with:
                subscriptionId: ${{ env.SUBSCRIPTION_ID_PROD }}
                resourceGroupName: ${{ env.RESOURCE_GROUP_PROD}}
                template: ./main.bicep
                parameters: ./parameters/prod.parameters.json appServiceAPIEnvVarENV=${{ env.ENV }} appServiceAPIEnvVarDBHOST=${{ env.DBHOST }} appServiceAPIEnvVarDBNAME=${{ env.DBNAME }} appServiceAPIEnvVarDBPASS=${{ secrets.DBPASS }} appServiceAPIDBHostDBUSER=${{ secrets.DBUSER }} appServiceAPIDBHostFLASK_APP=${{ env.FLASK_APP }} appServiceAPIDBHostFLASK_DEBUG=${{ env.FLASK_DEBUG }}
                deploymentName: ${{ env.USER_ALIAS }}
      
            
      